services:
  postgres-master:
    build: ./database_master
    container_name: postgres-master
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pg_master_data:/var/lib/postgresql/data
      - ./database_master:/docker-entrypoint-initdb.d
    networks:
      - medicat_network

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    ports:
      - "${RABBITMQ1_PORT}:${RABBITMQ1_PORT}"
      - "${RABBITMQ2_PORT}:${RABBITMQ2_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - medicat_network

  redis:
    build: ./redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - medicat_network

volumes:
  pg_master_data:
  rabbitmq_data:

networks:
  medicat_network:
